name: Claude Setup Compliance

on:
  push:
    branches: [main, develop, staging]
  pull_request:

jobs:
  compliance:
    name: Check Compliance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. CLAUDE.md CHECKS
      - name: Check CLAUDE.md exists
        run: |
          if [ ! -f "CLAUDE.md" ]; then
            echo "::error::CLAUDE.md not found"
            exit 1
          fi
          echo "✓ CLAUDE.md exists"

      - name: Verify required @imports
        run: |
          MISSING=""

          if ! grep -q "workflow.md" CLAUDE.md; then
            MISSING="$MISSING workflow.md"
          fi

          if ! grep -q "code-quality.md" CLAUDE.md; then
            MISSING="$MISSING code-quality.md"
          fi

          if [ -n "$MISSING" ]; then
            echo "::error::Missing imports in CLAUDE.md:$MISSING"
            exit 1
          fi
          echo "✓ Required @imports present"

      # 2. SECURITY CHECKS
      - name: Check app-config.yml
        run: |
          if [ ! -f ".github/app-config.yml" ]; then
            echo "::error::Missing .github/app-config.yml"
            exit 1
          fi

          VISIBILITY=$(grep "visibility:" .github/app-config.yml | cut -d: -f2 | tr -d ' ')

          if [ "$VISIBILITY" != "internal" ] && [ "$VISIBILITY" != "public" ]; then
            echo "::error::Invalid visibility '$VISIBILITY' - must be 'internal' or 'public'"
            exit 1
          fi

          echo "✓ Security config valid (visibility: $VISIBILITY)"

      # 3. CI/CD CHECKS
      - name: Check deploy workflow exists
        run: |
          if ls .github/workflows/deploy-*.yml 1> /dev/null 2>&1; then
            echo "✓ Deploy workflow found"
          else
            echo "::error::No deploy workflow found"
            exit 1
          fi

      # 4. VERSION CHECK (Warning only)
      - name: Check setup version
        continue-on-error: true
        run: |
          if [ ! -f ".claude/setup-version.yml" ]; then
            echo "::warning::No setup-version.yml found - consider running setup-claude.sh"
            exit 0
          fi

          LOCAL_VERSION=$(grep "version:" .claude/setup-version.yml | cut -d: -f2 | tr -d ' "')
          echo "✓ Setup version: $LOCAL_VERSION"
