# Lighthouse CI Workflow
# Copy to: .github/workflows/lighthouse.yml
#
# Runs Lighthouse audits after deployment to verify PWA score and performance

name: Lighthouse

on:
  # Run after deploy workflow completes
  workflow_run:
    workflows: [Deploy]
    types: [completed]
  # Manual trigger
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to audit'
        required: true

jobs:
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v4

      - name: Determine URL
        id: url
        run: |
          if [ -n "${{ github.event.inputs.url }}" ]; then
            echo "url=${{ github.event.inputs.url }}" >> $GITHUB_OUTPUT
          else
            # Default to production URL - customize for your app
            echo "url=${{ vars.PRODUCTION_URL || 'https://your-app.workers.dev' }}" >> $GITHUB_OUTPUT
          fi

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        id: lighthouse
        with:
          urls: ${{ steps.url.outputs.url }}
          budgetPath: ./lighthouse-budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Check PWA Score
        run: |
          PWA_SCORE=${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.pwa }}
          echo "PWA Score: $PWA_SCORE"
          if (( $(echo "$PWA_SCORE < 0.9" | bc -l) )); then
            echo "::warning::PWA score is below 90%: $PWA_SCORE"
          fi

      - name: Check Performance
        run: |
          PERF_SCORE=${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.performance }}
          echo "Performance Score: $PERF_SCORE"
          if (( $(echo "$PERF_SCORE < 0.8" | bc -l) )); then
            echo "::warning::Performance score is below 80%: $PERF_SCORE"
          fi

      - name: Comment PR with Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const results = ${{ steps.lighthouse.outputs.manifest }};
            const summary = results[0].summary;

            const body = `## 🔦 Lighthouse Results

            | Metric | Score |
            |--------|-------|
            | Performance | ${Math.round(summary.performance * 100)}% |
            | Accessibility | ${Math.round(summary.accessibility * 100)}% |
            | Best Practices | ${Math.round(summary['best-practices'] * 100)}% |
            | SEO | ${Math.round(summary.seo * 100)}% |
            | PWA | ${Math.round(summary.pwa * 100)}% |

            [View detailed report](${results[0].report})`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
